README.md
=> Document clearly to install a suitable Fidel iOS SDK version.

ios/RCTConvert+Country.h, package.json
=> fix(countries): fix typo sweeden -> sweden

android/build.gradle, example/package.json
=> Use the latest Android SDK to fix Android back button crash.

.gitignore, README.md, fidel-react-native.podspec, ios/FLRNCardSchemesFromJSAdapter.m, ios/FLRNCountryAdapter.h, ios/FLRNImageFromRNAdapter.m, ios/FLRNOptionsAdapter.m, ios/FLRNSetupAdapter.m, ios/Fidel.h, ios/Fidel.m, ios/Fidel.xcodeproj/project.pbxproj, ios/RCTConvert+CardScheme.h, ios/RCTConvert+Country.h, ios/RCTConvert+Options.h, package.json
=> Fix more contexts integration [MINOR]

CHANGELOG.md, android/src/test/java/com/fidelreactlibrary/WritableMapDataConverterTests.java, example/ios/File.swift, example/ios/Podfile, example/ios/Podfile.lock, example/ios/example-Bridging-Header.h, example/ios/example.xcodeproj/project.pbxproj, example/ios/example/Info.plist, example/package.json, package.json
=> Fix Android banner image issue in release environment [PATCH]

CHANGELOG.md, android/build.gradle
Improve French and Swedish translations coverage in more countries  [PATCH]
=> Update Android SDK version [PATCH]

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, example/package.json
Remove card scanning confirmation screen [MINOR]
=> Remove card scanning confirmation screen [MINOR]

CHANGELOG.md, android/build.gradle, android/src/main/java/com/fidelreactlibrary/adapters/FidelOptionsAdapter.java, example/App.js, example/ios/Podfile.lock, example/yarn.lock, ios/FLRNOptionsAdapter.m, ios/FLRNSDKOptions.h, ios/RCTConvert+Options.h, ios/RCTConvert+Options.m
Jira: [EM-508](https://fidel.atlassian.net/browse/EM-508)
Changelog:
Added property to set the default selected country.
=> EM 508 add property to specify default selected country

CHANGELOG.md, README.md, android/build.gradle, android/src/main/java/com/fidelreactlibrary/adapters/FidelOptionsAdapter.java, example/App.js, example/ios/Podfile.lock, example/yarn.lock, ios/FLRNOptionsAdapter.m, ios/FLRNSDKOptions.h, ios/RCTConvert+Options.h, ios/RCTConvert+Options.m
=> Add option to select the default selected country [MINOR]

.gitignore, CHANGELOG.md, android/build.gradle, android/src/main/java/com/fidelreactlibrary/adapters/WritableMapDataConverter.java, android/src/test/java/com/fidelreactlibrary/WritableMapDataConverterTests.java, example/App.js, example/ios/Podfile.lock, example/package.json, example/yarn.lock, package.json
Fix support for latest npm (Fixes #76)
Always provide the scheme field on Android.
[PATCH]
=> Release 1.6.1 [PATCH]

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, example/package.json, example/yarn.lock
=> Update Android bridge library to link to the latest Android SDK [PATCH]

android/build.gradle, example/.gitignore, example/android/app/src/main/AndroidManifest.xml, example/android/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties
Jira: [IDK-238](https://fidelapi.atlassian.net/browse/IDK-238)
Changelog:
Update Android build tools for the RN example project.
Update the Fidel Android SDK version that fixes the expiration date editing experience.
=> Update Android build tools. Update Fidel Android SDK version.

android/build.gradle, example/.gitignore, example/android/app/src/main/AndroidManifest.xml, example/android/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties
=> [PATCH] Allow expiration date editing without switching to country selector.

android/build.gradle, example/ios/Podfile.lock
Jira: [IDK-357](https://fidelapi.atlassian.net/browse/IDK-357)
Changelog:
Point to the latest released iOS and Android SDKs that contain a consent language update.
=> Point to the latest iOS & Android SDKs.

android/build.gradle, package.json
Update the rn sdk version and the Android version, the iOS is updated automatically
=> IDK-1532: update versions

android/src/main/java/com/fidelreactlibrary/FidelModule.java, android/src/main/java/com/fidelreactlibrary/FidelPackage.java, android/src/main/java/com/fidelreactlibrary/adapters/FidelCardVerificationChoiceAdapter.java, android/src/main/java/com/fidelreactlibrary/adapters/abstraction/CardVerificationChoiceAdapter.java, android/src/main/java/com/fidelreactlibrary/events/BridgeLibraryEvent.java, android/src/main/java/com/fidelreactlibrary/events/CardVerificationChoiceObserver.java, android/src/test/java/com/fidelreactlibrary/FidelModuleTests.java, android/src/test/java/com/fidelreactlibrary/adapters/FidelCardSchemesAdapterTests.java, android/src/test/java/com/fidelreactlibrary/adapters/FidelCardVerificationChoiceAdapterTest.java, example/App.js, index.js, ios/Constants/CardVerificationChoiceConstants.swift, ios/Constants/ExportedConstantsProvider.swift, ios/Events/BridgeLibraryEvent.swift, ios/Events/CardVerificationChoiceSelectedObserver.swift, ios/NativeFidelBridge.swift
Task https://fidelapi.atlassian.net/browse/CLET-97
=> CLET-97: added callback implementation for Android

android/build.gradle, android/src/main/java/com/fidelreactlibrary/FidelModule.java, example/ios/Podfile.lock, index.js, ios/NativeFidelBridge.m, ios/NativeFidelBridge.swift
Add new React Native function to be able to identify the react native data source name & version.
[Link to Jira ticket](https://fidelapi.atlassian.net/browse/CLET-195)
<details>
<ul>
<li>- [x] I have added metadata to the pull request, including assignees and labels.</li>
<li>- [x] I have added the Jira ticket link to the description and ticket id to the description.</li>
<li>- [x] I have tested the change in my local environment (compile and run).</li>
<li>- [ ] I have …
=> Identify the react native metrics data source.

android/build.gradle, example/App.js, example/ios/Podfile.lock
Add a description here.
[Link to Jira ticket](https://fidelapi.atlassian.net/browse/CLET-330)
<details>
<ul>
<li>- [ ] …
=> updated android SDK

android/build.gradle, example/App.js, example/ios/Podfile.lock
Release PR for the privacy changes
[Link to Jira ticket](https://fidelapi.atlassian.net/browse/CLET-330)
<details>
<ul> …
=> [PATCH] Release

android/build.gradle
Upgrade Android SDK version to latest
[Link to Jira ticket](https://fidel.atlassian.net/browse/)
<details>
<ul>
<li>- [ …
=> chore: upgrade android sdk version

android/build.gradle, example/package.json, package.json
Add a description here.
[Link to Jira ticket](https://fidel.atlassian.net/browse/)
<details>
<ul>
<li>- [ ] I have …
=> Release [PATCH]

README.md
- Update docs url 
[Link to Jira ticket](https://fidel.atlassian.net/browse/)
<details>
<ul>
<li>- [ ] I have performed …
=> docs: update readme docs url

android/build.gradle, android/src/main/java/com/fidelreactlibrary/adapters/FidelCountryAdapter.java, android/src/test/java/com/fidelreactlibrary/adapters/FidelCountryAdapterTests.java, example/ios/Podfile.lock, ios/Constants/CountryConstants.swift
Add new allowed country codes
[Link to Jira ticket](https://fidel.atlassian.net/browse/FT-749)
<details>
<ul>
<li>- [ ] …
=> feat: add new allowed country codes [MINOR]

example/package.json, package.json
Add a description here.
[Link to Jira ticket](https://fidel.atlassian.net/browse/)
<details>
<ul>
<li>- [ ] I have …
=> chore: bump package version [PATCH]

android/build.gradle, example/ios/Podfile.lock
Bump iOS and android SDKs versions
[Link to Jira ticket](https://fidel.atlassian.net/browse/FT-827)
<details>
<ul> …
=> chore: bump android and ios sdks
